[0m09:18:41.687770 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BAC598D490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BAC5994590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BAC59953D0>]}


============================== 09:18:41.691171 | fc06b3f6-0e0b-4dc2-985b-7d1be4ac5860 ==============================
[0m09:18:41.691171 [info ] [MainThread]: Running with dbt=1.7.13
[0m09:18:41.691171 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\josem\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt init demo_dbt', 'send_anonymous_usage_stats': 'True'}
[0m09:18:41.692988 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': WindowsPath('C:/Users/josem/.dbt')}
[0m09:18:41.693991 [info ] [MainThread]: Creating dbt configuration folder at 
[0m09:18:41.695390 [debug] [MainThread]: Starter project path: C:\Users\josem\OneDrive\Desktop\Projects\DBT Tutorial Project\dbt-env\Lib\site-packages\dbt\include\starter_project
[0m09:18:41.734829 [info ] [MainThread]: 
Your new dbt project "demo_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m09:18:41.735834 [info ] [MainThread]: Setting up your profile.
[0m09:30:15.137116 [error] [MainThread]: Encountered an error:

[0m09:30:15.147554 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\josem\OneDrive\Desktop\Projects\DBT Tutorial Project\dbt-env\Lib\site-packages\dbt\cli\requires.py", line 91, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\josem\OneDrive\Desktop\Projects\DBT Tutorial Project\dbt-env\Lib\site-packages\dbt\cli\requires.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\josem\OneDrive\Desktop\Projects\DBT Tutorial Project\dbt-env\Lib\site-packages\dbt\cli\main.py", line 515, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\josem\OneDrive\Desktop\Projects\DBT Tutorial Project\dbt-env\Lib\site-packages\dbt\task\init.py", line 344, in run
    self.setup_profile(profile_name)
  File "C:\Users\josem\OneDrive\Desktop\Projects\DBT Tutorial Project\dbt-env\Lib\site-packages\dbt\task\init.py", line 264, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "C:\Users\josem\OneDrive\Desktop\Projects\DBT Tutorial Project\dbt-env\Lib\site-packages\dbt\task\init.py", line 181, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "C:\Users\josem\OneDrive\Desktop\Projects\DBT Tutorial Project\dbt-env\Lib\site-packages\dbt\task\init.py", line 165, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\josem\OneDrive\Desktop\Projects\DBT Tutorial Project\dbt-env\Lib\site-packages\dbt\task\init.py", line 131, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "C:\Users\josem\OneDrive\Desktop\Projects\DBT Tutorial Project\dbt-env\Lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\josem\OneDrive\Desktop\Projects\DBT Tutorial Project\dbt-env\Lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m09:30:15.148056 [debug] [MainThread]: Command `dbt init` failed at 09:30:15.148056 after 693.48 seconds
[0m09:30:15.148056 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BABEBAA150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BADDE66850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001BAC599FAD0>]}
[0m09:30:15.148056 [debug] [MainThread]: Flushing usage events
[0m09:40:04.857603 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020442537F10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000204413B6510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020442014350>]}


============================== 09:40:04.861100 | b8766dbd-c71b-434e-a8bb-80db9d9132ce ==============================
[0m09:40:04.861100 [info ] [MainThread]: Running with dbt=1.7.13
[0m09:40:04.861100 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\josem\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m09:40:04.868161 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\josem\OneDrive\Desktop\Projects\DBT Tutorial Project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:40:04.868161 [debug] [MainThread]: Command `dbt run` failed at 09:40:04.868161 after 0.10 seconds
[0m09:40:04.871178 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002043B72A1D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002044251A090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002044251AE90>]}
[0m09:40:04.871178 [debug] [MainThread]: Flushing usage events
